### ISSUE TITLE
Error using template literal with constants in 0.4.1 (worked in 0.3.0)

### ISSUE THREAD

**Issue by medmunds** [pveyes/raw.macro#43]
This code worked in v0.3.0. It uses a template literal containing a constant, which resolves to a single file at compile time:

```typescript
const DEFAULT_LOCALE = 'en-US';
const DEFAULT_MESSAGES = raw(`./assets/locales/${DEFAULT_LOCALE}.ftl`);
```

I just tried upgrading to v0.4.1, and that code now generates the build error:

```text
Error: resources.ts: raw.macro: Cannot resolve file .ftl in these directories: en-US, fr Learn more: https://www.npmjs.com/package/raw.macro
    at Array.forEach (<anonymous>)
```

("en-US" and "fr" are the names of the two .ftl files in the ./assets/locales/ dir.)

Is this expected? Since I'm using a const in the template, I was hoping dynamic resolution wouldn't kick in.

(Thanks for this package, btw.)

**Comment by pveyes** [comment]
I don't think this is expected

As of 0.4.x we start treating template literal as a dynamic import, and your code should be transformed to

```js
const __raw_dynamic__0 = {
  'en-US': 'content'
}

const DEFAULT_LOCALE = 'en-US';
const DEFAULT_MESSAGES = __raw_dynamic__0[DEFAULT_LOCALE]
```

As you can see in https://github.com/pveyes/raw.macro/blob/68ece3f104cf5434cc4cdb57e29a270cbdc98d43/src/__tests__/__snapshots__/macro.test.js.snap#L54-L71

So even though the treatment is different, it still should resolve the same way.

Can you create a repro? probably in codesandbox or github

**Comment by medmunds** [comment]
Sure, here's a repro sandbox:
* with v0.4.1 (broken): https://codesandbox.io/s/raw-macro-template-literal-v04-6ii66?file=/src/locales.ts:192-270
* with v0.3.1 (working): https://codesandbox.io/s/raw-macro-template-literal-v03-27k4s?file=/src/locales.ts:126-204

I get a different error in codesandbox, but at the same place: `TypeError: /sandbox/src/locales.ts: raw.macro: r.readdirSync(...).filter(...).flatMap is not a function`. (codesandbox is running node v10.21.0; the original error I posted was from node v12.18.0. The sandboxes are create-react-app typescript projects, with the latest TypeScript 3.9.7 and a fresh `yarn update`.)

Related question: is it the case that starting with v0.4, if I use raw.macro with a template literal, it's going to compile in a `__raw_dynamic__` with the content of *every* possible matching file? (Even if the template literal compiles to a constant?) I ask, because I've been using raw.macro to compile in the resources from a *single* locale file in the directory, and then loading others at runtime through fetch, to avoid bloating my code. And I guess that won't work with v0.4? (The sandboxes demonstrate this approach.)

**Comment by pveyes** [comment]
Ok just did some digging, turns out the code fails in this line https://github.com/pveyes/raw.macro/blob/33689e2280ca8664027edcf57c0f730891b493f1/src/macro.js#L191

When the babel plugin is executed, it runs

```js
require.resolve('en.txt', {
  paths: ['/path/to/assets/locales']
})
```

and fails.

Not sure why it works in test, but adding relative path fixes it

```js
require.resolve('./en.txt', {
  paths: ['/path/to/assets/locales']
})
```

I'll make 2 changes:
 1. Make sure that template literal which can be transformed into constant will use constant instead. [This is](https://github.com/pveyes/raw.macro/pull/37/files#diff-d00ce319611f799416336e14835a2619L29) removed from 0.3.0 because I don't think there's any usage in constant template literal with variable
 2. Add relative path prefix to `require.resolve` to handle true dynamic import case

**Comment by medmunds** [comment]
Oh, outstanding! Thanks for the quick fix!
