### ISSUE TITLE
`Cannot find module 'raw.macro'` when upgrading from 0.4.2

### ISSUE THREAD

**Issue by EduardoBautista** [pveyes/raw.macro#61]
Had no other changes to my code. Very simple file:

```
import raw from "raw.macro";

const privacyPolicy = raw("./privacy_policy.md");
```

Works on 0.4.2 but not on 0.6.1.

`babel-plugin-macros` is at version 3.1.0.

**Comment by dahei** [comment]
I can confirm that bug/error. Had to downgrade to 0.4.2 to make it work in my CRA app.

**Comment by pveyes** [comment]
Hi, sorry everyone, seems like it was broken because I switched to `exports` field. Probably because it's not supported in few node versions

I've published 0.6.2 to add back the `main` field. Can you confirm whether this works?

Edit:
If it still doesn't work. Can you share your env? (node version, yarn/npm version, etc)

**Comment by dahei** [comment]
I tested the latest 0.6.2 and it works fine again :)

Thanks for the quick fix!

**Comment by pveyes** [comment]
Awesome

If it still doesn't work for some of you, please reopen this issue and share your env version

**Comment by soerface** [comment]
@pveyes it seems to be broken again with 0.7.0.

`npm i --save-dev raw.macro` will refuse installation:

```
…
npm ERR! Could not resolve dependency:
npm ERR! peerOptional babel-plugin-macros@"^2.8.0" from raw.macro@0.7.0
npm ERR! node_modules/raw.macro
npm ERR!   dev raw.macro@"0.7.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: babel-plugin-macros@2.8.0
npm ERR! node_modules/babel-plugin-macros
npm ERR!   peerOptional babel-plugin-macros@"^2.8.0" from raw.macro@0.7.0
npm ERR!   node_modules/raw.macro
npm ERR!     dev raw.macro@"0.7.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```

If I retry with `npm install --save-dev --legacy-peer-deps raw.macro`, npm doesn't complain anymore, but the package will not be found on application start (as described in the initial issue). But it will be listed in my `package.json` with `"^0.7.0"` and exists in `node_modules` in version `0.7.0`.

However, I can make it work by running `npm i --save-dev --legacy-peer-deps raw.macro@0.6.2`

My env:
- babel-plugin-macros: 3.1.0
- node: 16.16.0
- npm: 8.11.0
